### ISSUE TITLE
Oracle Cache: Data seems missing

### ISSUE THREAD

**Issue by sumodm** [vicariousinc/science_cognitive_programs#1]
Seems like the oracle_cache data seems missing. I get the following error

`[Errno 2] No such file or directory: 'oracle_cache/oracle_data_for_move_square_shape_to_upper_left_corner_and_circle_shape_to_upper_right_corner.pkl'`

From the name, I am assuming it is not generated data

**Comment by sumodm** [comment]
Gentle reminder on this ;) @vicarious-opensource 

If you can tell me where I can find the oracle_cache files or how I can create it. I tried giving just instructions for 546 concepts. But it seems like requires all possible paths on instructions graph, is this correct?

**Comment by vicarious-opensource** [comment]
The download location has been added to the README file https://github.com/vicariousinc/science_cognitive_programs/blob/master/README.md
